name: Node.js CI

on:
  pull_request:
    branches:
      - develop
      - production
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - closed
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
env:
  AWS_REGION: eu-west-2
  working_dir: "."

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '20.17.0'
        cache: 'npm'
    - uses: fregante/setup-git-user@v2
    - env:
        GITHUB_OBJ: ${{ toJson(github) }}
      run: echo "$GITHUB_OBJ"
    - name: Bump minor version
      run: scripts/version/release
      if: github.event.pull_request.base.ref == 'refs/heads/production' && startsWith(github.head_ref, 'release/')
    - name: Bump patch version
      run: scripts/version/hotfix
      if: github.event.pull_request.base.ref == 'refs/heads/production' && startsWith(github.head_ref, 'hotfix/')
    - name: Bump build version
      run: scripts/version/build
      if: github.event.pull_request.base.ref == 'refs/heads/develop'
    - name: Push version bump (PR merged)
      run: git push --follow-tags
      if: github.event.pull_request.merged == true
    - run: rm -rf node_modules/
    - run: npm install
    - run: rm -rf node_modules/
    - run: npm install --production
    - run: npm run package
    - uses: actions/upload-artifact@v4
      with:
        name: pre-s3-upload-artifact
        path: package.zip
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1
    - name: Set output npm package version
      id: output1
      run: echo "appver=${{ steps.package-version.outputs.current-version }}" >> $GITHUB_OUTPUT
    outputs:
      output1: ${{ steps.output1.outputs.appver }}

  package:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true || github.ref_type == 'tag'
    env:
      APPVER: ${{needs.build.outputs.output1}}
    steps:
      - run: echo "Packaging app version ${{ env.APPVER }}"
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Download packaged artifact
        uses: actions/download-artifact@v4
        with:
          name: pre-s3-upload-artifact

