name: Node.js CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
  pull_request:
    branches:
      - develop
      - production
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - closed
env:
  AWS_REGION: eu-west-2
  working_dir: "."

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v4
      - run: git branch --show-current
      - uses: actions/setup-node@v4
      - uses: fregante/setup-git-user@v2
      - name: Bump minor version
        run: scripts/version/release
        if: github.ref == 'refs/heads/production' && startsWith(github.head_ref, 'release/')
      - name: Bump patch version
        run: scripts/version/hotfix
        if: github.ref == 'refs/heads/production' && startsWith(github.head_ref, 'hotfix/')
      - name: Bump build version
        run: scripts/version/build
        if: github.ref == 'refs/heads/develop'
      - run: git push --follow-tags

  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: '20.17.0'
        cache: 'npm'
    - run: rm -rf node_modules/
    - run: npm install
    - run: rm -rf node_modules/
    - run: npm install --production
    - run: npm run package
    - uses: actions/upload-artifact@v4
      with:
        name: pre-s3-upload-artifact
        path: package.zip
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@v1.3.1
    - name: Set output npm package version
      id: output1
      run: echo "appver=${{ steps.package-version.outputs.current-version}}" >> $GITHUB_OUTPUT
    outputs:
      output1: ${{ steps.output1.outputs.appver }}

  package:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event.pull_request.merged == true
    needs: build
    env:
      APPVER: ${{needs.build.outputs.output1}}
    steps:
      - run: echo "Packaging app version ${{ env.APPVER }}"
      - uses: actions/checkout@v4
      - name: Download packaged artifact
        uses: actions/download-artifact@v4
        with:
          name: pre-s3-upload-artifact

