name: Node.js CI

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch'
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - uses: fregante/setup-git-user@v2
      - name: Set Up Node
        uses: actions/setup-node@master
        with:
          node-version: '16'
      - name: Get tag
        id: get-tag
        run: |
          TAGS=($(git tag --contains))
          TAG=${TAG[0]}
          if [ -z $TAG ]; then
            TAG=$(npm version patch)
            git push --follow-tags
          fi
          echo "Tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get-tag.outputs.tag }}
          generateReleaseNotes: true

