name: Deploy

on:
  workflow_dispatch:
    inputs:
      appver:
        description: 'App Version'
        required: true

permissions:
  id-token: write
  contents: write
  pull-requests: write

env:
  appver: ${{ inputs.app_ver }}
  skip_approval: ${{ inputs.app_ver }} == ""

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: APPVER
        run: echo ${{ env.appver }}
      - name: Approval
        if: ${{ env.skip_approval }} != true
        run: echo Approved
      - name: Approval Skipped
        if: ${{ env.skip_approval }} == true
        run: echo Approval skipped
