name: Bump Version

on:
  pull_request:
    branches:
      - develop
      - production
    types:
      - closed

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  bump-version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["20.17.0"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Git config
        env:
          PR_OBJ: ${{ toJson(github.event.pull_request) }}
        run: |
          echo "$PR_OBJ"
          git config --global user.name "${{ github.event.pull_request.merged_by.name }}"
          git config --global user.email "${{ github.event.pull_request.merged_by.email }}"
      - name: Bump minor version
        run: scripts/version/release
        if: github.ref == 'refs/heads/production' && startsWith(github.head_ref, 'release/')
      - name: Bump patch version
        run: scripts/version/hotfix
        if: github.ref == 'refs/heads/production' && startsWith(github.head_ref, 'hotfix/')
      - name: Bump build version
        run: scripts/version/build
        if: github.ref == 'refs/heads/develop'
      - name: Push version bump
        run: git push --follow-tags

